backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                ],
            }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: text },
                ],
            }
          - {
              label: Projects,
              name: projects,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: text },
                  {
                    label: Types,
                    name: types,
                    widget: list,
                    default:
                      [
                        "All",
                        "Kitchen",
                        "Bath",
                        "Floor",
                        "Fireplace",
                        "Specialty",
                      ],
                  },
                  {
                    label: Images,
                    name: images,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Type, name: type, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Testimonials,
                    name: testimonials,
                    widget: list,
                    fields:
                      [
                        { label: Quote, name: quote, widget: text },
                        { label: Author, name: author, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
      - file: "src/pages/gallery.md"
        label: "Gallery Page"
        name: "gallery"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery-page",
            }
      - file: "src/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
